# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Primeiros Socorros' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Primeiros Socorros

  pod 'DLRadioButton', '~> 1.4'
  pod 'Firebase/Core'

  target 'Primeiros SocorrosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
